{
				"numericDateOrder": ["d", "m", "y"],
				"numericDateSeparator": "\/",
				"shortDayNames": ["T2", "T3", "T4", "T5", "T6", "T7", "CN"],
				"timeSeparator": ":",
				"weekStart": 6,
				"formats": {
					"D": "D",
					"D g:ia": "D G:i",
					"D M d": "j F",
					"D M d, Y": "j F Y",
					"D M j": "j F",
					"D M j, g:ia": "j F G:i",
					"D M j, y": "j F Y",
					"D M j, Y g:ia": "j F Y G:i",
					"D, M j, Y": "j F Y",
					"F d": "j F",
					"F d, Y": "j F Y",
					"F g": "j F",
					"F j": "j F",
					"F j, Y": "j F Y",
					"F j, Y \u0040 g:i A": "j F Y G:i",
					"F j, Y g:i a": "j F Y G:i",
					"F jS": "j F",
					"F jS, g:ia": "j F G:i",
					"F jS, Y": "j F Y",
					"F Y": "F Y",
					"g A": "G",
					"g:i": "G:i",
					"g:i A": "G:i",
					"g:i a": "G:i",
					"g:iA": "G:i",
					"g:ia": "G:i",
					"g:ia F jS, Y": "j F Y G:i",
					"g:iA l, F jS": "j F Y G:i",
					"g:ia M j": "j F G:i",
					"g:ia M jS": "j F G:i",
					"g:ia, F jS": "j F G:i",
					"g:iA, l M jS": "j F Y G:i",
					"g:sa": "G:i",
					"H:I - M d, Y": "j F Y G:i",
					"h:i a": "G:i",
					"h:m:s m\/d\/Y": "d\/m\/Y H:i:s",
					"j": "j",
					"l F d, Y": "j F Y",
					"l g:ia": "l G:ia",
					"l, F d, Y": "j F, Y",
					"l, F j": "j F",
					"l, F j, Y": "j F Y",
					"l, F jS": "j F",
					"l, F jS, g:ia": "j F Y G:i",
					"l, M j": "j F",
					"l, M j, Y": "j F Y",
					"l, M j, Y g:ia": "j F Y G:i",
					"M d": "j F",
					"M d, Y": "j F Y",
					"M d, Y g:ia": "j F Y G:i",
					"M d, Y ga": "j F Y G",
					"M j": "j F",
					"M j, Y": "j F Y",
					"M j, Y g:i A": "j F Y G:i",
					"M j, Y g:ia": "j F Y G:i",
					"M jS, g:ia": "j F G:i",
					"M Y": "F Y",
					"M y": "j F",
					"m-d-y": "d\/m\/Y",
					"M. d": "j F",
					"M. d, Y": "j F Y",
					"j F Y": "j F Y",
					"m.d.y": "d\/m\/Y",
					"m\/d": "d\/m",
					"m\/d\/Y": "d\/m\/Y",
					"m\/d\/y": "d\/m\/Y",
					"m\/d\/Y g:ia": "d\/m\/Y H:i",
					"m\/d\/y H:i:s": "d\/m\/Y H:i:s",
					"m\/d\/Y h:m": "d\/m\/Y H:i:s",
					"n": "d\/m",
					"n\/j": "d\/m",
					"n\/j, g:ia": "d\/m\/Y H:i",
					"n\/j\/y": "d\/m\/Y",
					"Y": "Y",
					"Y-m-d": "d\/m\/Y",
					"Y\/m\/d": "d\/m\/Y",
					"y\/m\/d": "d\/m\/Y"
				},
				"ordinalSuffixes": {
					"1": "Ng\u00e0y 1",
					"2": "Ng\u00e0y 2",
					"3": "Ng\u00e0y 3",
					"4": "Ng\u00e0y 4",
					"5": "Ng\u00e0y 5",
					"6": "Ng\u00e0y 6",
					"7": "Ng\u00e0y 7",
					"8": "Ng\u00e0y 8",
					"9": "Ng\u00e0y 9",
					"10": "Ng\u00e0y 10",
					"11": "Ng\u00e0y 11",
					"12": "Ng\u00e0y 12",
					"13": "Ng\u00e0y 13",
					"14": "Ng\u00e0y 14",
					"15": "Ng\u00e0y 15",
					"16": "Ng\u00e0y 16",
					"17": "Ng\u00e0y 17",
					"18": "Ng\u00e0y 18",
					"19": "Ng\u00e0y 19",
					"20": "Ng\u00e0y 20",
					"21": "Ng\u00e0y 21",
					"22": "Ng\u00e0y 22",
					"23": "Ng\u00e0y 23",
					"24": "Ng\u00e0y 24",
					"25": "Ng\u00e0y 25",
					"26": "Ng\u00e0y 26",
					"27": "Ng\u00e0y 27",
					"28": "Ng\u00e0y 28",
					"29": "Ng\u00e0y 29",
					"30": "Ng\u00e0y 30",
					"31": "Ng\u00e0y 31"
				}
			}