__d("CometKeys", ["Locale"], (function (a, b, c, d, e, f) {
	"use strict";
	a = Object.freeze({
		COMMA: ",",
		DELETE: "backspace",
		DOWN: "arrowdown",
		END: "end",
		ENTER: "enter",
		ESCAPE: "escape",
		HOME: "home",
		LEFT: b("Locale").isRTL() ? "arrowright" : "arrowleft",
		NEXT: b("Locale").isRTL() ? "arrowleft" : "arrowright",
		PAGE_DOWN: "pagedown",
		PAGE_UP: "pageup",
		PREVIOUS: b("Locale").isRTL() ? "arrowright" : "arrowleft",
		QUESTION: "?",
		RIGHT: b("Locale").isRTL() ? "arrowleft" : "arrowright",
		SEMI_COLON: ";",
		SLASH: "/",
		SPACE: " ",
		TAB: "tab",
		UP: "arrowup",
		ONE: "1",
		TWO: "2",
		THREE: "3",
		FOUR: "4",
		FIVE: "5",
		SIX: "6",
		SEVEN: "7",
		EIGHT: "8",
		NINE: "9",
		ZERO: "0",
		A: "a",
		B: "b",
		C: "c",
		D: "d",
		E: "e",
		F: "f",
		G: "g",
		H: "h",
		I: "i",
		J: "j",
		K: "k",
		L: "l",
		M: "m",
		N: "n",
		O: "o",
		P: "p",
		Q: "q",
		R: "r",
		S: "s",
		T: "t",
		U: "u",
		V: "v",
		W: "w",
		X: "x",
		Y: "y",
		Z: "z"
	});
	c = a;
	e.exports = c
}), null);